### ISSUE TITLE
[web page] Text overlap and missing scroll for the menu

### ISSUE THREAD

**Issue by kpym** [pdfcpu/pdfcpu#272]
On the project web page https://pdfcpu.io the text "This project is maintained by pdfcpu" overlaps the manu if the resolution is not big enough. 

In the same conditions we can't access the bottom of the (unfolded) menu because the scroll works only on the right part of the page (the menu is not scroll-able).

You can see this behavior on high resolution screen when you zoom the web page.
![Screen_capture_2020-12-24](https://user-images.githubusercontent.com/3142701/103070537-fc5ead80-45c1-11eb-81e6-fef73fcf9ed0.png)

**Comment by hhrutter** [comment]
I am aware. 
This is due to Github pages and the Jackson static site generator they are using.
The plan is to eventually move pdfcpu.io away from this technology and revamp the site completely
but this is gonna take some time and until then we have to live with all involved artifacts and quirks.

**Comment by gernotstarke** [comment]
I cannot replicate this behavior in Chrome (v87.0),
but in both Firefox and Safari: The footer on the left navigation tree just moves upwards when the window is vertically resized.

**Comment by kpym** [comment]
@hhrutter I think you are talking about `Jakyll` not `Jackson` ;)

An easy fix will be to add in [custom.css](https://github.com/pdfcpu/pdfcpu/blob/gh-pages/css/common.css) of the `gh-pages` branch the following code 

```css
.wrapper {
    display: flex;
    flex-flow: row wrap;
    justify-content: center;
}

.wrapper header,
.wrapper section,
.wrapper footer
 {
    float:none;
    position:relative;
}
```

Sorry I have no time now to make a push request.
